---
# tasks file for bastion-preparation

- name: Installing Required Packages For Kubectl
  apt:
    pkg:
     - apt-transport-https
     - ca-certificates
     - curl
    state: present
    update_cache: yes

- name: Downloading Kubernetes GPG Key
  shell: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Adding Kubernetes Repo
  shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Installing Kubectl
  apt:
    pkg:
     - kubectl
    state: present
    update_cache: yes

