---
- name: Bootstraping GKE Cluster 
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/01-global_vars.yaml
    - vars/02-gke_vars.yaml
    - vars/03-gke_oauth_scopes.yaml
  roles:
    - gke-NETWORK
    - gke-FIREWALL
    - Bastion-NFS
    - gke-CLUSTER
    - gke-NodePool

