---
- name: Bootstraping GKE Cluster 
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/global_vars.yaml
    - vars/gke_vars.yaml
    - vars/gke_oauth_scopes.yaml
  roles:
    - gke-NETWORK
    - gke-FIREWALL
    - Bastion-NFS
    - gke-CLUSTER
    - gke-NodePool

- name: Bootstrapping Bastion
  hosts: bastion_hosts
  become: true
  gather_facts: false
  vars_files:
    - vars/global_vars.yaml
    - vars/gke_vars.yaml
    - vars/docker_vars.yaml
    - vars/nfs_ip.yaml
  roles:
    - Bastion-NFS-preparation
    - jenkins-master-IMAGE
    - Templating-Files

- name: Deploying NFS Provisioner & Jenkins Master 
  hosts: bastion_hosts
  become: true
  gather_facts: false
  vars_files:
    - vars/global_vars.yaml
    - vars/gke_vars.yaml
    - vars/docker_vars.yaml
    - vars/nfs_ip.yaml
  roles:
    - gke-NFS-provisioner
    - gke-JENKINS-Master-Deployment
    
