apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master-nfs-pvc
  namespace: jenkins-master
spec:
  volumeName: jenkins-master-nfs-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

