---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
    role: master
  name: jenkins-master-portal
  namespace: jenkins-master
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
    role: master
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
    role: master
  name: jenkins-master-jnlp
  namespace: jenkins-master
spec:
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins
    role: master
  type: ClusterIP

