---
# tasks file for gke-FIREWALL
#
- name: Creating External Firewall Rules For Network {{ gke_network.name }}
  google.cloud.gcp_compute_firewall:
    name: "{{ gke_network.name }}-allow-{{ item.key }}"
    source_ranges:
      - 0.0.0.0/0
    allowed:
    - ip_protocol: "{{ item.value.ip_protocol }}"
      ports:
        - "{{ item.value.port }}"
    network:
     selfLink: "{{ gke_network.selfLink }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  loop: "{{ lookup('dict', firewall_rules_external) }}"

- name: Creating External ICMP Firewall Rule For Network {{ gke_network.name }}
  google.cloud.gcp_compute_firewall:
    name: "{{ gke_network.name }}-allow-icmp"
    source_ranges:
      - 0.0.0.0/0
    allowed:
    - ip_protocol: icmp
    network:
     selfLink: "{{ gke_network.selfLink }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- name: Creating Internal Firewall Rules For Network {{ gke_network.name }}
  google.cloud.gcp_compute_firewall:
    name: "{{ gke_network.name }}-allow-internal"
    source_ranges:
      - 10.128.0.0/9
    allowed:
    - ip_protocol: all
    network:
     selfLink: "{{ gke_network.selfLink }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
